title: Eric Choi
#logo: 
description: |
  Student at the University of Pennsylvania pursuing a MSE in Data Science and a BA in Economics with minors in Mathematics and Statistics.   
#show_downloads: true
theme: jekyll-theme-minimal
