title: Eric Choi
#logo: 
description: I am currently a senior at the University of Pennsylvania pursuing a BA in economics with minors in mathematics and statistics. Concurrently,, I am pursuing a MSE in data science in the school of engineering. 
#show_downloads: true
theme: jekyll-theme-minimal
