title: Eric Choi
#logo: 
description: |
  Student at the University of Pennsylvania pursuing a Master of Science in Data Science, with a strong background in Economics and Mathematics. My studies focus on advanced data analysis techniques and machine learning algorithms. I have developed expertise through coursework in Applied Machine Learning, Databases for Analytics, and Artificial Intelligence, among other relevant subjects. I am passionate about leveraging data to drive insights and solve complex problems. 
#show_downloads: true
theme: jekyll-theme-minimal
