title: Eric Choi
logo: /images/headshot3.png
logo_class: site-logo
description: |
  Student at the University of Pennsylvania pursuing a MSE in Data Science and a BA in Economics with minors in Mathematics and Statistics.   
#show_downloads: true
theme: jekyll-theme-minimal

links:
  - title: "Resume"
    url: /images/Eric Choi - Resume.pdf  # Adjust this path based on where you uploaded the resume
    icon: fa-solid fa-file-pdf
