title: Eric Choi
#logo: 
description: BA in Economics with Minors in Mathematics and Statistics, MSE in Data Science at the University of Pennsylvania.
description: Relevant Coursework: Applied Machine Learning, Databases for Analytics, Artificial Intelligence, Modern Data Mining, Data Analytics and Statistical Computing, Econometric Methods and Models
#show_downloads: true
theme: jekyll-theme-minimal
