title: Eric Choi
#logo: 
description: BA in *Economics* with Minors in *Mathematics and Statistics*, MSE in *Data Science* at the University of Pennsylvania.
#show_downloads: true
theme: jekyll-theme-minimal
